### ISSUE TITLE
Add preview route without login like tumblr 

### ISSUE THREAD

**Issue by KarlsDaddy** [yTakkar/React-Instagram-Clone-2.0#10]
It‘s possible to create a preview route (Maybe below the Login.hbs) from some content like tumblr.
![5baaf829-85fb-46b8-b91a-b4725eea972c](https://user-images.githubusercontent.com/33890798/36640675-e40d1978-1a23-11e8-8b63-939a3c0d0e7f.jpeg)
After Click of a content item (e.g. Heart-Icon or username) the User have to verified by his User and password.

can you give me a hint for code Adaptation

**Comment by Butonix** [comment]
Where admin panel?

**Comment by KarlsDaddy** [comment]
what do you mean?

**Comment by Runixuz** [comment]
how to install this fayl

**Comment by KarlsDaddy** [comment]
fayl :)?
