### ISSUE TITLE
admin panel

### ISSUE THREAD

**Issue by Runixuz** [yTakkar/React-Instagram-Clone-2.0#11]
I love this script ... but add admin panels.
or is it present?

**Comment by yTakkar** [comment]
No it's not present, I'll working on it very soon..

**Comment by Runixuz** [comment]
great
Thanks for answering my question

**Comment by Runixuz** [comment]
Created using Nodejs?

**Comment by Runixuz** [comment]
Do you have a video for installation?
For beginners

**Comment by yTakkar** [comment]
Yes, back-end is powered by NodeJS.
No there's no video for installation, but the process is quite straight-forward.

**Comment by Runixuz** [comment]
yes

**Comment by Runixuz** [comment]
Do you work in the "hamp"?

**Comment by Runixuz** [comment]
xampp

**Comment by Runixuz** [comment]
....

**Comment by yTakkar** [comment]
Added admin system https://github.com/yTakkar/React-Instagram-Clone-2.0/commit/07bed552b4bb6c70b7901b4d4b5ebd95091783a9

**Comment by Runixuz** [comment]
accellent****
