### ISSUE TITLE
yarn or npm start error

### ISSUE THREAD

**Issue by Runixuz** [yTakkar/React-Instagram-Clone-2.0#13]

**Comment by Runixuz** [comment]
yarn or npm start eroor 

\React-Instagram-Clone-2.0-master>npm start

> react-instagram-clone-2.0@1.0.0 start D:\инс\React-Instagram-Clone-2.0-master
> nodemon app.js

'nodemon' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-instagram-clone-2.0@1.0.0 start: `nodemon app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-instagram-clone-2.0@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Davron\AppData\Roaming\npm-cache\_logs\2018-03-12T09_55_32_411Z-debug.log

**Comment by yTakkar** [comment]
install `nodemon` globally by `npm i -g nodemon`
