### ISSUE TITLE
Can i use it on Ubuntu 16.04?

### ISSUE THREAD

**Issue by JimmyFellan** [yTakkar/React-Instagram-Clone-2.0#16]
Hello my friend,
As first, you created awesome script. I want to test it for fun on my server, so i must ask you.

Can i use it on Ubuntu 16.04 with Apache2, PHP 7, MySQL, Node.js, npm?
It's all what i need? (Except requirements what you have noticed)?
Thanks :-)

**Comment by yTakkar** [comment]
I think yes.
You only need, nodejs, phpmyadmin

**Comment by JimmyFellan** [comment]
Thank you, but everytime, when i run `handy-client-env` i get this error
`handy-client-env
/usr/local/lib/node_modules/handy-client-env/client-env.js:5
  { success, error } = require('handy-log'),
  ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
`

**Comment by JimmyFellan** [comment]
Sorry bro solved, i must update node.js to newest version :-)

**Comment by JimmyFellan** [comment]
So ok, im stupid or i dont know :-D Can you please help me with this?
When i execute npm start this will happen:

> root@vm24666:/usr/web# npm start
> react-instagram-clone-2.0@1.0.0 start /usr/web
> nodemon app.js
sh: 1: nodemon: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-instagram-clone-2.0@1.0.0 start: `nodemon app.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the react-instagram-clone-2.0@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-22T12_28_01_134Z-debug.log

Log:

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.7.1
3 info using node@v9.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-instagram-clone-2.0@1.0.0~prestart: react-instagram-clone-2.0@1.0.0
6 info lifecycle react-instagram-clone-2.0@1.0.0~start: react-instagram-clone-2.0@1.0.0
7 verbose lifecycle react-instagram-clone-2.0@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle react-instagram-clone-2.0@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/web/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle react-instagram-clone-2.0@1.0.0~start: CWD: /usr/web
10 silly lifecycle react-instagram-clone-2.0@1.0.0~start: Args: [ '-c', 'nodemon app.js' ]
11 info lifecycle react-instagram-clone-2.0@1.0.0~start: Failed to exec start script
12 verbose stack Error: react-instagram-clone-2.0@1.0.0 start: `nodemon app.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:180:13)
12 verbose stack     at maybeClose (internal/child_process.js:936:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
13 verbose pkgid react-instagram-clone-2.0@1.0.0
14 verbose cwd /usr/web
15 verbose Linux 4.4.0-97-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v9.9.0
18 verbose npm  v5.7.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error react-instagram-clone-2.0@1.0.0 start: `nodemon app.js`
23 error spawn ENOENT
24 error Failed at the react-instagram-clone-2.0@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by yTakkar** [comment]
First install nodemon by `npm i nodemon -g`

**Comment by ApertureSecurity** [comment]
I am working on getting this to run in Ubuntu. I will open a new issue and will probably be opening a PR once I make a few changes.

 It looks like this was written in a Windoze environment , IE not suitable for any prod environment.

**Comment by ApertureSecurity** [comment]
I am going to open an issue on this because I can probably fix this myself , but I want to be sure with the bug that I have.

**Comment by ApertureSecurity** [comment]
Moved part of this to this issue....

https://github.com/yTakkar/React-Instagram-Clone-2.0/issues/19

**Comment by ApertureSecurity** [comment]
Ok following up here because I managed to get it working.... Some minor touchups are needed to make this useble in Linux in general.

In the db.sql script find this

```
CREATE TABLE `groups` (
  `group_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `bio` varchar(2000) NOT NULL,
  `admin` int(11) NOT NULL,
  `group_type` enum('public','private') NOT NULL DEFAULT 'public',
  `created` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

Remove the NOT NULL from bio and it launched fine... The problem was that it expects you to have filled out a bio and that doesn't happen in the registration process...

You MIGHT need to  go into the users table and change the email_verified set to yes.

```

CREATE TABLE `groups` (
  `group_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `bio` varchar(2000),
  `admin` int(11) NOT NULL,
  `group_type` enum('public','private') NOT NULL DEFAULT 'public',
  `created` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

```

**Comment by ApertureSecurity** [comment]
Actually there is something to my answer that might be wrong.... 


In mysql 11 I am still experiencing this same thing. I am reopening this to resolve this issues. 

Perhaps it's a security mismatch... somewhere...

**Comment by ApertureSecurity** [comment]
No I'm a dumbass... They're something larger here and I think it's a conflict of mysql versions.  I will reopen issue the other issue.

**Comment by JimmyFellan** [comment]
Apertute, you can open another. But are not allowed to get support from author. Because he is not selling this script. He is giving this script for free. So his support is only his good decision ;-)

**Comment by ApertureSecurity** [comment]
I wasnt asking for support entirely. If you look closely at my comments, I was finding problems and returning solutions.

Despite this being free, I think it should be in better condition than it is , or be marked deprecated or failing and not supported , of the author intends this to be the case.

Ultimately  , after completing my review of the code, I went with something that was written with a much better potential to become production code one day.

**Comment by ApertureSecurity** [comment]
I felt like If I was going to try this out , I could at least provide some support.

Anyway the the db script needs to have the null values removed or something because it's incompatible with what it's code requires.
