### ISSUE TITLE
 ER_NO_DEFAULT_FOR_FIELD: Field 'bio'

### ISSUE THREAD

**Issue by ApertureSecurity** [yTakkar/React-Instagram-Clone-2.0#19]
Hey going through your code....

When I try to register on my built version , it crashes with...

This is usually caused from an Insert that is missing a default value. What is missing from this? Surely this would be a known issue.
`
(node:16876) UnhandledPromiseRejectionWarning: Error: ER_NO_DEFAULT_FOR_FIELD: Field 'bio' doesn't have a default value at Query.Sequence._packetToError (/home/appsec/Desktop/React-Instagram-Clone-2.0/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14) at Query.ErrorPacket (/home/appsec/Desktop/React-Instagram-Clone-2.0/node_modules/mysql/lib/protocol/sequences/Query.js:77:18) at Protocol._parsePacket (/home/appsec/Desktop/React-Instagram-Clone-2.0/node_modules/mysql/lib/protocol/Protocol.js:279:23) at Parser.write (/home/appsec/Desktop/React-Instagram-Clone-2.0/node_modules/mysql/lib/protocol/Parser.js:76:12) at Protocol.write (/home/appsec/Desktop/React-Instagram-Clone-2.0/node_modules/mysql/lib/protocol/Protocol.js:39:16) at Socket.<anonymous> (/home/appsec/Desktop/React-Instagram-Clone-2.0/node_modules/mysql/lib/Connection.js:103:28) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) at readableAddChunk (_stream_readable.js:250:11) -------------------- at Protocol._enqueue (/home/appsec/Desktop/React-Instagram-Clone-2.0/node_modules/mysql/lib/protocol/Protocol.js:145:48) at Connection.query (/home/appsec/Desktop/React-Instagram-Clone-2.0/node_modules/mysql/lib/Connection.js:208:25) at Promise (/home/appsec/Desktop/React-Instagram-Clone-2.0/config/db.js:13:8) at new Promise (<anonymous>) at Object.query (/home/appsec/Desktop/React-Instagram-Clone-2.0/config/db.js:12:10) at bcrypt.hash (/home/appsec/Desktop/React-Instagram-Clone-2.0/config/User.js:23:10) at /home/appsec/Desktop/React-Instagram-Clone-2.0/node_modules/bcrypt-nodejs/bCrypt.js:631:3 at _combinedTickCallback (internal/process/next_tick.js:131:7) at process._tickCallback (internal/process/next_tick.js:180:9) (node:16876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:16876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by yTakkar** [comment]
I think default value of `bio` should be set to `null`. I never got this error, so I didn't set the default value to null.

**Comment by ApertureSecurity** [comment]
Ok. I am looking for where this is set. 

I will get back to you on this.

**Comment by ApertureSecurity** [comment]
That isn't what your db.sql suggests....

```
CREATE TABLE `groups` (
  `group_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `bio` varchar(2000) NOT NULL,
  `admin` int(11) NOT NULL,
  `group_type` enum('public','private') NOT NULL DEFAULT 'public',
  `created` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

```

I will look further.

**Comment by ApertureSecurity** [comment]
Anyway I removed the NOT null from the bio setting and it launched fine.

**Comment by ApertureSecurity** [comment]
We can close this . Perhaps a PR is needed . I will let you decide how you want to step with this.

**Comment by ApertureSecurity** [comment]
Yeah can I reopen this? 

It appears they're conflicts in many places and I think this is meant for lower than version 11 of mysql. I had better success on version 9 but am now looking.

**Comment by ApertureSecurity** [comment]
errors like this are giving me the idea that this isn't meant for this version.

 `Error: ER_FIELD_IN_ORDER_NOT_SELECT: Expression #1 of ORDER BY clause is not in SELECT list, references column 'socialnetwork.hashtags.hashtag_time' which is not in SELECT list; this is incompatible with DISTINCT...`


also in routes/user-routes.js  you have this...

   ```
 newUser = {
          username,
          firstname,
          surname,
          email,
          password,
          joined: new Date().getTime(),
          email_verified: 'no'

```

The database is set other values going into the users tables are NOT NULL... so of course this is breaking....

We can get around this by doing the following though...


  ```
     let
        newUser = {
          username,
          firstname,
          surname,
          email,
          password,
          bio:"",
          instagram:"",
          facebook:"",
          twitter:"",
          github:"",
          phone:"",
          website:"",
          joined: new Date().getTime(),
          email_verified: 'no'
        },
        { insertId, affectedRows } = await User.create_user(newUser),
        mkdir = promisify(fs.mkdir)
     let
        newUser = {
          username,
          firstname,
          surname,
          email,
          password,
          bio:"",
          instagram:"",
          facebook:"",
          twitter:"",
          github:"",
          phone:"",
          website:"",
          joined: new Date().getTime(),
          email_verified: 'no'
        },
        { insertId, affectedRows } = await User.create_user(newUser),
        mkdir = promisify(fs.mkdir)

```
