### ISSUE TITLE
uploading photo error

### ISSUE THREAD

**Issue by BagasNS** [yTakkar/React-Instagram-Clone-2.0#2]
when im post photo in localhost the app freeze at posting menu. when im check the console its say

(node:1396) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "
-quality" "100" "C:\Users\DIEVIRA\Downloads\Compressed\React-Instagram-Clone-2.0
-master\public\temp\97d6933d99bee10a2dcd9562687ab1a1" "-gravity" "NorthWest" "C:
\Users\DIEVIRA\Downloads\Compressed\React-Instagram-Clone-2.0-master/public/post
s/instagram_1518272820657.jpg" this most likely means the gm/convert binaries ca
n't be found
(node:1396) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code
any solution? im trying to make a social app for my school so hope u want to help me with your project @yTakkar

**Comment by yTakkar** [comment]
For the first time I'm seeing this type of error

**Comment by yTakkar** [comment]
Ohh I see, have you installed gm libraries? Sorry I forgot to add it as a requirement.
Have a look at it here: [gm](http://aheckmann.github.io/gm/), it says you must first install GraphicsMagick or ImageMagick.

**Comment by BagasNS** [comment]
thanks guys its working well...great job and ill waiting next update maybe u want add video post and insta story feature
