### ISSUE TITLE
Re - Change in code does not reflect

### ISSUE THREAD

**Issue by firetick** [yTakkar/React-Instagram-Clone-2.0#24]
I am running code as 
Npm Start dev - Code is running fine,

When i change Style.css file , it reflects in app immediately.
Buy if i change some text like below in \public\js\src\components\others\header.js
This is not reflected 
Note : I have changed text - Settings to SettingsChange.

```
<li className='o_li'>
              <a href='/settings' className='o_a' alt='SettingsChange'>SettingsChange</a>
            </li> 
```

Can anyone guide me for this
Thanks
Arjun

**Comment by yTakkar** [comment]
Run 'npm start' for starting the server.
'npm run dev' for bundling client-side JS files.
That's it

**Comment by yTakkar** [comment]
I tested the app and it worked fine.
`Settings` link is on 2 components, sidebar & header (Inside drop-down menu). 
I think you changed the text of settings link in the header component & looked for change in the sidebar component.

**Comment by firetick** [comment]
Thanks @yTakkar for info.
After running code with 'npm run dev'
I am getting below error.
NOTE : I have installed webpack-cli with 'npm i webpack-cli', still same error.

npm run dev

> react-instagram-clone-2.0@1.0.0 dev E:\FIRETICK\React-Instagram-Clone-2.0
> webpack -d --watch

The CLI moved into a separate package: webpack-cli
Would you like to install webpack-cli? (That will run yarn add -D webpack-cli) (yes/NO)yes
yarn add v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > babel-loader@7.1.2" has unmet peer dependency "webpack@2 || 3".
warning " > webpack-cli@2.0.14" has unmet peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ webpack-cli@2.0.14
info All dependencies
└─ webpack-cli@2.0.14
Done in 8.48s.
{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at runCommand.then.result (C:\Users\arjun\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:62:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-instagram-clone-2.0@1.0.0 dev: `webpack -d --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-instagram-clone-2.0@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\arjun\AppData\Roaming\npm-cache\_logs\2018-04-16T07_51_50_325Z-debug.log

**Comment by yTakkar** [comment]
Since `webpack` is installed globally, so you have to install `webpack-cli` globally by `npm i webpack-cli -g`

**Comment by firetick** [comment]
i think it is not able to get path of .env file.
Any suggestions..?

**Comment by yTakkar** [comment]
You first follow all the instructions.
Follow instruction no. 5
