### ISSUE TITLE
picture upload. Please wait

### ISSUE THREAD

**Issue by Runixuz** [yTakkar/React-Instagram-Clone-2.0#26]
![untitled11](https://user-images.githubusercontent.com/28822563/38859641-e298c154-4247-11e8-85ed-26f309ffa95a.png)

**Comment by Runixuz** [comment]
![untitled11](https://user-images.githubusercontent.com/28822563/38859736-1fcf1258-4248-11e8-888d-c6eaf407ada4.png)

**Comment by Butonix** [comment]
Install GraphicsMagick
https://github.com/yTakkar/React-Instagram-Clone-2.0#requirements

**Comment by yTakkar** [comment]
Is there any error message in the terminal?

**Comment by Runixuz** [comment]
There is no error in the terminal

**Comment by yTakkar** [comment]
image posted?
image uploaded to `public/posts`?

**Comment by Runixuz** [comment]
no

**Comment by yTakkar** [comment]
Then that's a problem with `gm`

**Comment by yTakkar** [comment]
@Butonix is right
https://github.com/yTakkar/React-Instagram-Clone-2.0/issues/26#issuecomment-382024214
