### ISSUE TITLE
some dependency error

### ISSUE THREAD

**Issue by rcdosado** [yTakkar/React-Instagram-Clone-2.0#28]
correct me if i'm wrong but it seems that handy-client-env is not included in the dependencies?thanks for this project!

**Comment by yTakkar** [comment]
`Handy-Client-Env` had to installed globally so it wasn't listed in the package.json .  
Now I've modified the package and can be installed locally as well. 
Now, it' included.
https://github.com/yTakkar/React-Instagram-Clone-2.0/commit/fe66e2f5a3b8d99c58f7647b0be2ed11f34498ea
