### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by chaoman** [yTakkar/React-Instagram-Clone-2.0#37]
Thanks for the help. Finally got your react app running but I got the following mysql client error every time when I start the app. 

```
chaoman@ubuntu_server_nodejs:~/React-Instagram-Clone-2.0$ sudo npm start        
> react-instagram-clone-2.0@1.0.0 start /home/chaoman/React-Instagram-Clone-2.0
> nodemon app.js

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
**ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client**
App running..
```

I am using mysql client that installed from Ubuntu 18's repo
```mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper```

Any tip would be appreciated.

**Comment by yTakkar** [comment]
You have some error in your configuration

**Comment by chaoman** [comment]
After some digging, it turned out that I had to add the following SQL command to MySQL server running on Ubuntu 18. 

```
use mysql;
update user set authentication_string=password(''), plugin='mysql_native_password' where user='root';

```
Make sure that you enter the password inside the ('').
