### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by magentodallas** [yTakkar/React-Instagram-Clone-2.0#39]
So I have followed all the steps and get to APP is running with rainbow colors.. 

I visit my localhost + port and just get the file directory?

What am I missing?

Is there a certain folder to execute npm start in or do I need to bundle the package or what step is needed that is NOT mentioned in the 7 steps under usage?

**Comment by yTakkar** [comment]
If you've followed all the steps, then it should work.

**Comment by magentodallas** [comment]
Lol WTF that’s all the help I get lol

Thanks,
Vangeli Gelekas 
469-647-1669
twitter.com/netgenius
linkedin.com/in/netgenius
magentodallas.com
