### ISSUE TITLE
Adding new fields and section

### ISSUE THREAD

**Issue by StarAzure** [yTakkar/React-Instagram-Clone-2.0#46]
Nice work. Looking to add new fields but did not see any config in admin panel. I added the new fields in db.sql, added in social-inputs, edit-profile.js but new fields not showing up.
How to add new fields for user profile and add new sections such as "Personal" , "Business" etc..
Thanks

**Comment by ismanoor** [comment]
you need to compile the those files or their respective folders into bundle.js using webpack plugin, For more detail and understanding please consider this issue: #45

**Comment by StarAzure** [comment]
I had to run dev build to get it to work. I didn't think I have to because create-react-app have hot reloading that don't have a bundle js until you build.

**Comment by yTakkar** [comment]
@StarAzure this app was not bootstrapped with create-react-app.
