### ISSUE TITLE
Uppercase chars in fields gets stripped on update profile

### ISSUE THREAD

**Issue by StarAzure** [yTakkar/React-Instagram-Clone-2.0#47]
When saving user profile characters gets deleted if it is uppercase

**Comment by yTakkar** [comment]
Yes it ensures users have legal username.
Only small letters, numbers, _.@$# are allowed.

If you want to allow Uppercase letters also, edit [this line](https://github.com/yTakkar/React-Instagram-Clone-2.0/blob/master/routes/api/others/edit-routes.js#L37)  to `/[^a-zA-Z0-9_.@$#]/g`
