### ISSUE TITLE
Visitor of a profile can see Edit profile buttons and edit field links in About page

### ISSUE THREAD

**Issue by StarAzure** [yTakkar/React-Instagram-Clone-2.0#48]
When a user visits another user's profile, the edit button and edit profile is enabled for that user. The visitor should not be allowed to see the edit profile button and field edit links for another user.

**Comment by yTakkar** [comment]
Oh thnx for this critical issue.
I'll surely fix it by today.

**Comment by StarAzure** [comment]
I fixed this by using "Me" created two about sections - one read only and other normal one.
