### ISSUE TITLE
User remains logged in for hours which is a security issue. 

### ISSUE THREAD

**Issue by StarAzure** [yTakkar/React-Instagram-Clone-2.0#49]
Users should be logged out when idle after a specific time. I noticed the users never get logged out. This might pose security code concerns. Thanks.

**Comment by yTakkar** [comment]
By default user is logged-in for 24 hours.
If you wanna change it to let's say 1 hour, go ahead and edit [this line](https://github.com/yTakkar/React-Instagram-Clone-2.0/blob/master/app.js#L53) to `1 * 60 * 60 * 1000`
