### ISSUE TITLE
Uploading Videos

### ISSUE THREAD

**Issue by itsmidnightyo** [yTakkar/React-Instagram-Clone-2.0#5]
UI is looking very nice, along with the entire idea + features this clone has to offer.
Do you plan on implementing support for uploading videos and a way to categorize/filter between them? (example being: view photos/videos only from each user / from the explore page?)

**Comment by yTakkar** [comment]
I'll add video uploading feature soon..

**Comment by MindfulMe** [comment]
Is there any progress? We can help
