### ISSUE TITLE
Image dimensions in gallery do not maintain aspect ratio

### ISSUE THREAD

**Issue by StarAzure** [yTakkar/React-Instagram-Clone-2.0#50]
The react image gallery that is used is fed with settings height=15 and width=15. When a user uploads an image that is 600px wide and 400px tall, it is getting distorted into a square image and not maintaining the aspect ratio. How can this be fixed ?

**Comment by yTakkar** [comment]
This is a base project, anyone can modify and use this project according to their needs.

**Comment by StarAzure** [comment]
I agree, this project is not close to being production ready. Bugs like these needs to be fixed.

**Comment by yTakkar** [comment]
This is not a bug but something that can be improved.
