### ISSUE TITLE
Explore image shows image but no username or profile link.

### ISSUE THREAD

**Issue by StarAzure** [yTakkar/React-Instagram-Clone-2.0#51]
Explore images shows a bunch of images but no information related to it... In instagram or facebook for example, when someone opens an image, it shows the user who posted the image and comments.. Not having comments is fine for images but an overlay with username and link to user profile should be there. I don't think just showing random images without any links to user is useful.

**Comment by yTakkar** [comment]
Did you clicked on any of the image?

**Comment by yTakkar** [comment]
Click on an image, you'll see a modal pop up with essential information

**Comment by StarAzure** [comment]
I found the bug - I changed css for .img_s_bottom to bottom: 100px and it shows the information. I am going to try to display this even before the modal is displayed.

.image_show .img_s_bottom {
    position: absolute;
    bottom: 100px;

**Comment by yTakkar** [comment]
It works when perfectly fine when image is clicked.

![alt text](https://image.ibb.co/izRotd/Snap_2018_07_22_at_20_39_02.png)

**Comment by StarAzure** [comment]
Thats because your image is not tall enough. If the image is taller it pushes that text below the view..

**Comment by yTakkar** [comment]
Oh never had this issue before, thnx for bringing it up.
There should be a solution for this specific case
