### ISSUE TITLE
Cannot find main.hbs

### ISSUE THREAD

**Issue by dwasse** [yTakkar/React-Instagram-Clone-2.0#75]
I believe to have installed all dependencies correctly (on ubuntu 18.04), but after running npm start and loading localhost:1157 in my browser, I get this message:

`Error: ENOENT: no such file or directory, open '/React-Mini-Social-Network/views/layouts/main.hbs`

This file indeed does not exist. Why is the initial page directing me to main.hbs? Any ideas? Thanks!

**Comment by vincentroman** [comment]
this a different repo

**Comment by utkarshboson** [comment]
> I believe to have installed all dependencies correctly (on ubuntu 18.04), but after running npm start and loading localhost:1157 in my browser, I get this message:
> 
> `Error: ENOENT: no such file or directory, open '/React-Mini-Social-Network/views/layouts/main.hbs`
> 
> This file indeed does not exist. Why is the initial page directing me to main.hbs? Any ideas? Thanks!

Hey
Did you find a fix for this ?

Thanks

**Comment by dwasse** [comment]
This seemed to work for some reason, still not totally sure what the issue was. May have been platform dependent (running Ubuntu on WSL):
```
npm env
npm run dev
ctrl + c
npm start
```
