### ISSUE TITLE
npm run dev - webpack - no starting local web-dev-server

### ISSUE THREAD

**Issue by KarlsDaddy** [yTakkar/React-Instagram-Clone-2.0#9]
if i run by
`npm run dev` 
Files are generated / compiled by webpack fine - so far so good.

But the  --watch (webpack -d --watch) parameter does not work for me, 

I meant,
1. actually a local web server would have to start with
2. the app.js would have to be run (like localhost: 9999 -> .env vars?)

**Comment by yTakkar** [comment]
Actually, there's no web-dev-server in this project. You have to run `yarn start` to run the app and `yarn dev` to bundle js files.

**Comment by KarlsDaddy** [comment]
thanks!
