### ISSUE TITLE
Dark Mode Toggle

### ISSUE THREAD

**Issue by gauravgupta98** [yTakkar/React-Instagram-Clone-2.0#97]
Can we have dark mode toggle on the application. Keeping the settings to be set according to System's settings and a override option also will be nice to have.

**Comment by nishant3721** [comment]
@gauravgupta98 Can I work on it?

**Comment by gauravgupta98** [comment]
Hi @nishant3721 ,
Yes, I think it will be great if you can. But I think we should get this confirmed first from the author @yTakkar .

What are your thoughts on this @yTakkar ?

**Comment by nishant3721** [comment]
Ok...np!
